= Аннотация

В данном разделе представлена документация модуля {dv} 5. Консоль управления (далее -- Консоль управления или модуль).

Консоль управления предназначена для автоматизации работы администраторов системы {dv}, связанной с настройкой компонентов системы {dv}, мониторингом функционирования её процессов и компонентов, отслеживанием ошибок.

.Модуль предоставляет следующие функции:
* xref:user:worker-service.adoc[Настройка] конфигурации Службы {ws}.
* Просмотр очереди xref:user:msg-incoming.adoc[входящих] и xref:user:msg-outgoing.adoc[исходящих] сообщений Службы {ws}.
* Просмотр сообщений Службы {ws} и ошибок, связанных с определённой карточкой.
* Просмотр блокировок, установленных на карточки, с возможностью их снятия.
* Мониторинг нагрузки на Службу {ws}.

== Область применения

Модуль {wac} предназначен для использования в организациях, эксплуатирующих программные продукты компании ДоксВижн: систему {dv}, модуль Служба {ws} и др.

== Уровень подготовки пользователей

Пользователь Консоли управления должен обладать навыками установки и администрирования системы {dv} и её дополнительных модулей, а также установки программных продуктов в ОС Windows.

== Назначение документации

Документация содержит инструкцию по xref:admin:installation.adoc[установке] и xref:admin:provide-access.adoc[первоначальной настройке] модуля, а также инструкцию по работе с модулем: список решаемых задач, xref:user:user-interface.adoc[описание пользовательского интерфейса], xref:user-functions.adoc[инструкция по использованию].

== Как организована документация

.Настоящее руководство содержит следующие разделы:
. Общие сведения -- xref:admin:requirements.adoc[перечислены требования] к программному и аппаратному обеспечению компьютера для установки модуля, к лицензии и модулям {dv}.
. xref:admin:installation.adoc[] -- содержит инструкцию по установке и первоначальной настройке модуля.
. Функции администратора -- перечислены основные функции администратора модуля.
. xref:admin:potential-errors.adoc[Возможные ошибки] -- приведен список ошибок, которые могут возникать в работе сервиса Консоли управления, и пути их решения.
. xref:architecture.adoc[Структура модуля] -- кратко описана структура модулКонсоли управления.
. xref:user-functions.adoc[Выполняемые функции и задачи] -- приведено краткое описание возможностей модуля.
. xref:user:first-launch.adoc[Первый запуск] -- указаны действия при первом запуске.
. xref:user:user-interface.adoc[Интерфейс пользователя] -- приведено описание пользовательского интерфейса.
. Описание операций -- содержит описание общих операций в Консоли управления, инструкции по настройке подключений (к серверу {dv}, почтовому серверу и др.), формированию _дашборда_, работе с виджетами и настройке Службы {ws}.
. xref:user:Exceptions.adoc[Сообщения об ошибках] -- перечислены возможные ошибки при работе с Консолью управления и пути их решения.
