= Аннотация

== Назначение документа

Настоящий документ является руководством администратора модуля Docsvision 5. Консоль управления Docsvision (далее – Консоль управления, Модуль).

Документ содержит инструкцию по установке и первоначальной настройке модуля. Инструкция по работе с модулем приведена в Руководстве пользователя.

== Как организован документ

Настоящее руководство содержит следующие разделы:

. xref:admin:GeneralInformation.adoc[Общие сведения] (приведены общие сведения о Консоли управления, перечислены требования к программному и аппаратному обеспечению компьютера для установки Модуля).
. xref:admin:Structure.adoc[Структура модуля] (перечислены составные части Консоли управления).
. xref:admin:Installation.adoc[Установка и настройка] (содержит инструкцию по установке и первоначальной настройке модуля).
. xref:admin:Administration.adoc[Функции администратора] (перечислены основные функции администратора модуля).
. xref:admin:PossibleErrors.adoc[Возможные ошибки] (приведен список ошибок, которые могут возникать в работе сервиса Консоли управления, и пути их решения).

== Соглашения по оформлению

* *Жирный* – используется при написании названий элементов экранного интерфейса и выделения *важной информации*;
* _Курсив_ – используется для обозначения новых терминов, названий типов и видов карточек;
* http://docsvision.com[Синий] – используется для выделения перекрестных ссылок внутри документа и ссылок на доступные внешние документы, для указания адресов интернет-страниц;
* `Моноширинный` – используется для выделения текстов макрокоманд и программных кодов, имен файлов и путей к ним.