= Общие сведения о модуле

В данном разделе представлена документация модуля _{mc}_.

{mc} предназначена для автоматизации работы администраторов системы {dv}, связанной с настройкой компонентов системы {dv}, мониторингом функционирования её процессов и компонентов, отслеживанием ошибок.

.Модуль предоставляет следующие функции:
* xref:user:worker.adoc[Настройка] конфигурации Службы {ws}.
* Просмотр очереди xref:user:msg-incoming.adoc[входящих] и xref:user:msg-outgoing.adoc[исходящих] сообщений Службы {ws}.
* Просмотр сообщений Службы {ws} и ошибок, связанных с определённой карточкой.
* Просмотр блокировок, установленных на карточки, с возможностью их снятия.
* Мониторинг нагрузки на Службу {ws}.

== Область применения

Модуль {mc} предназначен для использования в организациях, эксплуатирующих программные продукты компании ДоксВижн: систему {dv}, модули _Служба {ws}_, _{ad}_, _{bo}_ и др.

== Уровень подготовки пользователей

Пользователь {of-mc} должен обладать навыками установки и администрирования системы {dv} и её дополнительных модулей, а также установки программных продуктов в ОС Windows и ОС Linux.

== Назначение документации

Документация содержит инструкцию по xref:admin:install.adoc[установке] и xref:admin:provide-access.adoc[первоначальной настройке] модуля, а также инструкцию по работе с модулем: список решаемых задач, xref:user:user-interface.adoc[описание пользовательского интерфейса], xref:user-functions.adoc[инструкция по использованию].

[#arrangement]
== Как организована документация модуля

.Настоящая документация содержит следующие разделы:
. Общие сведения -- xref:requirements.adoc[перечислены требования] к программному и аппаратному обеспечению компьютера для установки модуля, к лицензии и модулям {dv}.
. "xref:admin:install.adoc[]" -- содержит инструкцию по установке и первоначальной настройке модуля.
. "xref:admin:settings-storage-url.adoc[]" -- приводится инструкция по настройке адреса подключения к _{to-sett-serv}_.
//. xref:admin:.potential-errors.adoc[Возможные ошибки] -- приведён список ошибок, которые могут возникать в работе сервиса {of-mc}, и пути их решения.
. "xref:module-structure.adoc[Структура модуля]" -- кратко описана структура модуля _{mc}_.
. "xref:user-functions.adoc[Выполняемые функции и задачи]" -- приведено краткое описание возможностей модуля.
. "xref:user:first-launch.adoc[Первый запуск]" -- указаны действия при первом запуске.
. "xref:user:user-interface.adoc[Интерфейс пользователя]" -- приведено описание пользовательского интерфейса.
. Описание операций -- содержит описание общих операций в {of-mc}, инструкции по настройке подключений (к серверу {dv}, почтовому серверу и др.), формированию _дашборда_, работе с виджетами и настройке Службы {ws}.
