= Требования к установке модуля

[#hardware]
== Необходимое техническое обеспечение

Специальные требования к техническому обеспечению не предъявляются.

[#software]
== Необходимое программное обеспечение

Операционная система::
// * Microsoft Windows Server {server} и выше.
* Astra Linux Special Edition {l-1} и выше.


Обязательное программное обеспечение::
* {asp-bundle}.

Для работы в Консоли настройки {dv} необходим один из следующих веб-браузеров:

* Google Chrome {chrome-v} и выше.
* Microsoft Edge {edge-v} и выше.

[#network]
== Требования к ЛВС

.В локальной сети организации должны быть разрешены подключения:
* С компьютера с установленным модулем _{mc}_ ко всем управляемым экземплярам модуля _Служба {ws}_.
* HTTP-подключения к компьютеру с Консолью управления на порт `5100`.

[#license]
== Лицензия

Для работы с модулем {mc} лицензия не требуется.

После активации новой лицензии {dv} нужно перезапустить службу *{wacs}*.

[#docsvision]
== Требования к системе {dv}

Для работы модуля {mc} требуется версия модуля _Служба {ws}_ не ниже {ws-req}.
