= Требования к установке модуля

[#hardware]
== Необходимое техническое обеспечение

Специальные требования к техническому обеспечению не предъявляются.

[#software]
== Необходимое программное обеспечение

Операционная система::
* Microsoft Windows Server {server} и выше.
Обязательное программное обеспечение::
* .NET Framework {dotnetf-v}
* ASP.NET Core Runtime {asp-bundle} Hosting Bundle.

Для работы в Консоли настройки {dv} необходим один из следующих веб-браузеров:

* Google Chrome {chrome-v},
* Microsoft Edge {edge-v}.

[#network]
== Требования к ЛВС

.В локальной сети организации должны быть разрешены подключения:
* С компьютера с установленным модулем _{wac}_ ко всем управляемым экземплярам модуля _Служба {ws}_.
* HTTP-подключения к компьютеру с Консолью управления на порт `5100`.

[#license]
== Лицензия

Для работы с модулем {wac} лицензия не требуется.

После активации новой лицензии {dv} нужно перезапустить службу {wacs-g} в службах Windows.

[#docsvision]
== Требования к системе {dv}

Для работы модуля {wac} требуется версия модуля Служба {ws} не ниже 5.5.2.
