= Выполняемые функции и задачи

.Базовые функции {of-mc}:
Аутентификация пользователя::
Данная функция решает задачу ограничения xref:admin:provide-access.adoc[доступа] пользователей к {of-mc}. Аутентификация выполняется автоматически при подключении пользователя путём проверки вхождения его в ожидаемую группу безопасности.

Настройка соединений с внешними системами::
Службе {dv} и её компонентам, настраиваемым с помощью _{of-mc}_, может требоваться доступ к внешним системам (например, почтовому серверу). Данная задача решается с помощью xref:user:settings.adoc[соединений], в которых хранятся параметры подключений к внешним системам.

Протоколирование операций::
Изменения, выполненные пользователем протоколируются в xref:user:logs.adoc[журнале операций].
+
.Функции для настройки и мониторинга работы системы {dv} и её компонентов:
* Функции для работы со _Службой {ws}_ (входят в состав модуля _{mc}_).
* Настройка конфигурации _Сервиса {ws}_.
+
Пользователь может подключать новые экземпляры Сервиса {ws}, добавлять и настраивать _фоновые операции_.

Предоставление информации о загрузке Служб {ws}::
Анализ текущего состояния обработки задач подключенными _Службами {ws}_ с использованием _Виджетов_ и _Информационных страниц_ с очередями входящих и исходящих сообщений.

Поиск неисправности в процессах обработки бизнес-задач::
Для анализа причин возникновения нештатных ситуации пользователю предоставляются возможности xref:user:block-error-log.adoc[просматривать сообщения и ошибки], связанные с определённой карточкой.
