= Выполняемые функции и задачи

.Базовые функции Консоли управления:
Аутентификация пользователя::
Данная функция решает задачу ограничения xref:admin:provide-access.adoc[доступа] пользователей к Консоли управления. Аутентификация выполняется автоматически при подключении пользователя путём проверки вхождения его в ожидаемую группу безопасности (используется встроенная аутентификация Windows).

Настройка соединений с внешними системами::
Службе {dv} и её компонентам, настраиваемым с помощью Консоли управления, может требоваться доступ к внешним системам (например, почтовому серверу). Данная задача решается с помощью xref:user:connections.adoc[соединений], в которых хранятся параметры подключений к внешним системам.

Протоколирование операций::
Изменения, выполненные пользователем протоколируются в xref:user:console-log.adoc[журнале операций].
+
.Функции для настройки и мониторинга работы системы {dv} и её компонентов:
* Функции для работы со Службой {ws} (входят в состав модуля {wac}).
* Настройка конфигурации Сервиса {ws}.
+
Пользователь может подключать новые экземпляры Сервиса {ws}, добавлять и настраивать _фоновые операции_.

Предоставление информации о загрузке Служб {ws}::
Анализ текущего состояния обработки задач подключенными Службами {ws} с использованием _Виджетов_ и _Информационных страниц_ с очередями входящих и исходящих сообщений.

Поиск неисправности в процессах обработки бизнес-задач::
Для анализа причин возникновения нештатных ситуации пользователю предоставляются возможности xref:user:block-error-log.adoc[просматривать сообщения и ошибки], связанные с определённой карточкой.
