= Утилита WebToolUtil

Утилита DVWebTool прекращает развитие в пользу DVSupService, сборка DVWebTool при помощи Панели управления {wc}ом не поддерживается в версиях {wc}а без Панели управления. Для сборки DVWebTool без Панели управления предназначена утилита WebToolUtil.

.WebToolUtil необходимо запускать для повторной сборки DVWebTool в следующих случаях:
. Когда изменились файлы DVWebTool или вышла новая версия.
. Когда изменился адрес или порт вервера {wc}а.
. Когда изменились внутренние расширения утилит.

Новая версия WebToolUtil выпускается при каждом исправлении DVWebTool в накопительных обновлениях. Для распространения WebToolUtil могут использоваться групповые политики. WebToolUtil запускается на ОС Windows и выполняет функцию сборки DVWebTool. Утилита WebToolUtil включает все компоненты {wc}а, необходимые для сборки DVWebTool.

.Интерфейс WebToolUtil представлен следующими элементами:
* Поле _Адрес сервера {wc}а_ -- предназначено для указания URL сервера, на котором установлен {wc}.
* Поле _Порт DvWebTool_ -- предназначено для указания порта для подключения к серверу {wc}а.
* Кнопка *Соединиться* -- нажатие на кнопку устанавливает подключение к серверу {wc}а.
* Кнопка *Собрать DvWebTool* / *Пересобрать DvWebTool* -- кнопка сборки становится активной после успешной установки соединения. Полученные после сборки файлы нужно будет самостоятельно скопировать на сервер {wc}а.

Поведение DVWebTool при запуске настраивается в настройках {wc}а в {of-mc}, см. подробнеее в разделе "xref:dev@mgmtconsole:servers:webclient-tools.adoc#webtool[Автоматический запуск DVWebTool]".
