= Страница "Сервер приложений"

Настройки сервера дублируют аналогичные в программе "{cns}" для ОС Windows. Структура настроек на странице частично соответствует аналогичной в Консоли настройки.

NOTE: Все описанные настройки хранятся в Сервисе настроек и могут также дублироваться в конфигурационных файлах модулей. Настройки в конфигурационном файле имеют приоритет по сравнению с настройками в Сервисе настроек. Если настройка отсутствует в конфигурационном файле, но присутствует в Сервисе настроек, она будет получена из Сервиса настроек.

Интерфейс страницы настроек Сервера приложений представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования. Если компонент редактирования отсутствует, для настройки отображается поле ввода текста.

В шапке страницы расположены кнопки *Отменить* и *Применить*. При нажатии *Применить* отображается сообщение `Изменения на данной странице, вступят в силу после перезапуска службы *{sss-new}*`. Все настройки сохраняются в Сервисе настроек после перезапуска службы *{sss-new}*.

При нажатии *Отменить* отменяются все сделанные пользователем изменения.

[#license]
== Настройки лицензии

Блок настроек лицензии позволяет ознакомиться с информацией о текущей лицензии, назначить или снять назначенгие персональной лицензии. Подробнее см. в разделе "xref:appserver-license.adoc[]".

[#access]
== Управление доступом

Настройки подключения пользователей к серверу приложений. Подробнее см. "xref:appserver-access.adoc[]".

[#database]
== Настройки баз данных

Настройка баз данных, сюда входят создание, обновление и подключение. Подробнее см. "xref:db-settings.adoc[Настройки баз данных]".

[#general-settings]
== Группа "Общие настройки"

Общие настройки сервера приложений, включая "Адрес сайта документации", имя и пароль системной учётной записи и т.д. Подробнее см. "xref:appserver-general.adoc[]".

[#extensions]
== Расширенная аутентификация

Настройка сторонних расширений авторизации для входа в {wc}. Подробнее см. "xref:appserver-auth-extensions.adoc[]".

[#additional]
== Дополнительные настройки

Прочие настройки сервера приложений. См. подробнее "xref:appserver-etc.adoc[]"
