= Общие настройки сервера приложений

* В поле _Адрес сайта документации_ указывается адрес, по которому располагается документация системы. Поле поддерживает шаблоны расположения документации. Подробнее см. "xref:docs-location.adoc[]".
* Кнопка "Восстановить по умолчанию" -- восстанавливает стандартные настройки сервера, сбрасывает значения всех полей на заводские.
* Логин системной учётной записи -- поле для ввода имени системной учётной записи {dv} в формате `user@domain.com`.
* Пароль системной учетной записи -- поле для ввода пароля системной учётной записи {dv}. Рекомендуется хранить в зашифрованном виде. Подробнее про шифрование см. в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".
* Штамп сертификата шифрования паролей -- отпечаток закрытого ключа шифрования SHA1. Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно не указывать.
* Имя компьютера в текущем домене Active Directory -- необходимо для указания имени любого компьютера в текущем домене Active Directory. Используется при получении списка доступных членов домена при настройке дискреционной безопасности.
* API-ключ для подключения к Workflow -- API-ключ для подключения серверного расширения {wf}. Главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые.
* Следующие настройки входят в группу _Журналирование_:
** Файл журнала -- путь к файлу журнала, в котором регистрируются выполняемые сервером операции. По умолчанию используется: `/var/log/docsvision/platform/dvappserver.log`.
** Уровень журналирования -- кнопки выбора глубины фиксации процессов в журнале сервера приложений. По умолчанию используется: `Error`.
+
.Доступные варианты:
*** *Отключено*
*** *Ошибки*
*** *Предупреждения*
*** *Сообщения*
*** *Подробное* журналирование
+
* Следующие настройки входят в группу _Модули_:
** Проверка версии БД -- когда флаг установлен, сообщение о несоответствии версии базы данных и версии сервера {dv} вносится в журнал выполняемых сервером операций.
** Проверять версию базы данных -- когда флаг установлен, сообщение о несоответствии версии базы данных и версии сервера {dv} вносится в журнал выполняемых сервером операций.
** Обновление БД -- флаг включает режим установки модулей без загрузки данных в БД. По умолчанию флаг активирован.
** Пропускать обновление БД при установке модулей -- флаг отключает обновление БД при установке модулей. По умолчанию флаг неактивен.
* Следующие настройки входят в группу "Локализация полей":
** Язык -- язык локализации по умолчанию. По умолчанию используется Русский. Чтобы изменить язык локализации по умолчанию, измените значение параметра на: Русский, English. Подробнее см. "xref:default-localization.adoc[]".
** Режим локализации полей -- установка локализованных значений для полей клиентского приложения. Подробнее см. "xref:default-localization.adoc[]".
+
.Доступные варианты:
*** *Выкл*
*** *Чтение*
*** *Запись*
*** *Вкл*
*** *Особый* режим
