= Настроить режим локализации полей

В системе {dv} поддерживается возможность установки локализованных значений для полей. Фактическое возвращаемое сервером значение поля определяется локалью клиентского приложения.

.Системная функция локализации полей используется для локализации следующих элементов:
* Названий папок.
* Названий представлений и групп представлений.
* Названий столбцов и текста в строках агрегации значений в представлениях.
* Названий поисковых запросов и групп запросов.

[#function]
== Функция локализации полей

.Функция локализации полей работает следующим образом:
* Запустите {wincl} с текущей локалью и задайте имя объекта из списка в описании функции.
* Затем запустите {wincl} с другой локалью и задайте имя на этот же объект на другом языке.
* Каждой локали, заданной в {wincl}е, будет соответствовать имя объекта на своём языке.
+
Если локализованное значение отсутствует, будет возвращено значение для локали по умолчанию.

.По умолчанию используются следующие настройки локализации полей:
* Функция локализации полей отключена.
* Язык локализации по умолчанию -- *Русский*.

[WARNING]
====
Локализованные значения поля хранятся в отдельной секции. На чтение секции требуется дополнительное время. Это влияет на скорость работы с данными.

Значение поля для основной локали хранится в основной секции. Доступ к основной секции осуществляется в обычном режиме и не влияет на скорость работы с данными.
====

[#modify]
== Изменить настройки режима локализации полей по умолчанию

.Чтобы изменить настройки режима локализации полей по умолчанию:
. Откройте {mc} на странице menu:Серверы[Имя-сервера > Сервер приложений].
. Перейдите к группе настроек _Общие настройки_.
. Чтобы изменить язык локализации по умолчанию, измените значение настройки "menu:Локализация полей[Язык]" на:
* *Русский*,
* *English*.
+
. Чтобы изменить режим локализации, измените значение параметра `Режим локализации полей`:
+
* *Выкл* -- режим локализуемых полей выключен.
* *Чтение* -- только чтение локализуемых полей.
* *Запись* -- только запись локализуемых полей.
* *Вкл* -- режим локализуемых полей включён.
* *Особый* -- режим локализуемых полей включён с особым режимом. Новое значение поля будет сохраняться и для основной локали и для локали клиентского приложения.
+
. Перезапустите *{sss-new}*.
+
WARNING: Если система {dv} работает в кластере, выполните аналогичные настройки на всех серверах кластера {dv}.
