= Изменить расположение пользовательской документации

При обращении к документации из программ {wincl} и {wc}, пользователь по умолчанию будет направлен на https://docsvision.com[сайт компании ДоксВижн].

При необходимости администратор может разместить документы на ресурсах своей организации. Для этого необходимо изменить шаблон, по которому определяется расположение документации.

* Расположение пользовательской документации можно изменить через графический интерфейс {of-mc}, см. подробнее ниже.
* Альтернативный способ -- указать адрес документации в конфигурационном файле {wincl}а по адресу `/usr/lib/docsvision/platform/config/installers-windowsclient.json`, в параметре `"HelpUrl"`.

[#templates]
== Шаблоны расположения документации

Перейдите на страницу menu:Серверы[Имя-сервера > Сервер приложений > Общие настройки]. Укажите расположение документации в поле _Адрес сайта документации_.

.В поле могут быть использованы переменные:
* `\{client}` -- псевдоним клиентской программы, который может приобретать значения:
** `winclient` -- для {wincl}а.
** `webclient` -- для {wc}а.
+
[NOTE]
====
Другие клиентские приложения не поддерживают настройку, определяющую расположение документации.
====
+
* `\{version}` -- версия клиентской программы.

Таким образом фактический стандартный адрес документации, к примеру, для модуля {pl} версии {page-version} будет следующим: `\http://help.docsvision.com/platform/{page-version}/`.

WARNING: Для всех клиентских программ используется общий шаблон, поэтому размещать документацию {wincl}а и {wc}а следует на одном сайте.

[#deploy-docs]
== Требования к сборке сайта документации

Документация {dv} разворачивается с помощью https://docs.antora.org/[генератора статических сайтов Antora].
Документация может быть развёрнута локально, в таком случае потребуется изменить адрес документации в файле `https://github.com/Docsvision/antora-playbook/blob/083db793049a159db9b4c526ce5b1f3a58870c39/antora-playbook.yml#L24[antora-playbook.yml]`.

.Требования для сборки сайта:
* Доступ к сайту Github или иной доступ к https://github.com/Docsvision?q=antora-&type=all&language=&sort=[репозиториям] исходного кода документации {dv}. +
Репозитории документации обозначены префиксом `antora-`. Полный список источников указан в файле `https://github.com/Docsvision/antora-playbook/blob/083db793049a159db9b4c526ce5b1f3a58870c39/antora-playbook.yml#L24[antora-playbook.yml]` репозитория antora-playbook.
+
* Установлен git.
* Установлен Node.js версии, указанной в разделе "https://docs.antora.org/antora/latest/install/windows-requirements/[Требования]" на сайте документации Antora.
* Доступ к локальной копии репозитория https://github.com/Docsvision/antora-playbook/[Docsvision/antora-playbook/].

.Сборка и разворачивание документации:
. Откройте командную строку с расположением в корне репозитория `Docsvision/antora-playbook/`
. Установите Antora командой:
+
 npm i
+
. Запустите сборку сайта при помощи Antora, выполнив следующую команду:
+
 npx antora antora-playbook.yml
+
. Файлы сайта будут расположены в папке `wwwroot`.

[#view]
=== Просмотр сайта

.Сайт можно просматривать:
* Локально -- нажмите на сгенерированные html-файлы, расположенные в папке `wwwroot`.
* С простого http-сервера -- выполните шаги, https://docs.antora.org/antora/latest/preview-site/#run-a-local-server-optional[указанные в инструкции Antora].
* Иным способом. В результате сборки сайта формируются файлы в формате `.html`, которые могут доставляться любым удобным способом.

[#limitations]
=== Ограничения

.После сборки сайта некоторые функции окажутся недоступны:
* Поиск по сайту.
* Просмотр страниц накопительных обновлений.

Чтобы воспользоваться функциями локального (офлайн) поиска, рекомендуется использовать расширение Antora Lunr Search. Подробная инструкция по разворачиванию приведена в https://www.npmjs.com/package/antora-lunr[документации] расширения.
