= Настройка "Р7-Офис" в {of-mc}

Данный раздел описывает установку и настройку "Р7-Офис. Сервер документов" (далее "Р7-Офис") в {of-mc}, а также подготовку {wc}а для использования функций предварительного просмотра и консолидации.

[WARNING]
====
* Р7-Офис должен быть установлен на машину с сервером {wc}а.
+
** Если версия {wc}а *выше* {wc-r7}, Р7-Офис можно устанавливать отдельно от сервера {wc}а.
+
** Если версия {wc}а *ниже* {wc-r7}, Р7-Офис необходимо устанавливать на сервер {wc}а. Если Р7 будет установлен отдельно от серверных компонентов {dv}, функции консолидации и объединения версий не будут работать. Также могут возникать проблемы с редактированием файла. Аналогичное поведение будет наблюдаться, если в конфигурационном файле указать адрес Р7 офиса, установленного на другой машине Linux.
+
* Для установки Р7-Офис требуется минимальная версия ОС Astra Linux 1.7.3.
====

Р7-Офис или "OnlyOffice" используется для предварительного просмотра файлов в карточках и для консолидации версий документов при согласовании.

Предварительный просмотр при помощи Р7-Офис или OnlyOffice позволяет отображать предпросмотр не печатной версии документа, а непосредственно файла. Р7-Офис позволяет скопировать данные из документа Excel с сохранением структуры и форматирования. Некоторые функции ограничены возможностями Р7, например, новый компонент не поддерживает функцию поворота на 90 градусов.

NOTE: Р7-Офис может быть установлен и настроен самостоятельно по инструкции ниже или можно сразу подключиться к активному серверу Р7. Если планируется подключаться к активному серверу, перейдите сразу к <<address,указанию адреса>> Р7 Сервера документов в конфигурационном файле {wc}а.

[#install]
== Установка Р7-Офис

.Чтобы настроить работу Р7-Офис для включения предварительного просмотра и работы консолидации:
. Установите Р7-Офис согласно официальной инструкции на https://support.r7-office.ru/document_server/install-document_server/document_server_linux/install_ds_astalinux_debian_ubuntu/[сайте Р7-Офис]. Потребуется лицензия на Р7-Офис. В случае установки лицензии в ручном режиме, дополнительно может потребоваться назначить права на файл `license.lic`:
+
 chmod 644 /var/www/r7-office/Data/license.lic
+
. Если все действия выполнены правильно, при открытии в браузере адреса `\http://localhost:port` появится сообщение "Сервер документов запущен".
. [[consolidation]]Создайте файл конфигурации для Р7-Офис `/etc/nginx/includes/ds-docsvision.conf`.
. Выполните команду, чтобы новый конфигурационный файл прочитался:
+
 systemctl reload nginx
+
. В конфигурационный файл добавьте следующие строки:
+
[source]
----
location ~* ^(\/upload.*)(\/.*) {
  alias /tmp$1$2;
  add_header Content-Disposition "attachment; filename*=UTF-8''$arg_filename";
}
----
+
. В файле `/etc/r7-office/documentserver/local.json` задайте для параметров `inbox`, `outbox` и `browser` значение `false`.
// следующей командой:
// +
//  echo r7-office-documentserver-ee ds/jwt-enabled select false | sudo debconf-set-selections
// +
Затем перезапустите службу сервера документов:
+
 sudo systemctl restart ds-docservice.service
+
****
Если Р7-Офис и {wc} находятся на одной машине и для связи между собой используют один частный IP адрес, для корректного отображения предварительного просмотра необходимо изменить значение следующих параметров в файле `/etc/r7-office/documentserver/default.json`:

[source,json]
----
"request-filtering-agent" : {
  "allowPrivateIPAddress": false,
  "allowMetaIPAddress": false
},
----

По умолчанию значение параметров установлено в `false`, необходимо изменить его на `true`.

После изменения параметров необходимо перезапустить службы командами:

  sudo service nginx restart && sudo supervisorctl restart all
****
+
. В целях повышения безопасности настоятельно рекомендуется перевести сервер документов на использование HTTPS. Если переводить сервер документов на HTTPS не планируется, перейдите к пункту <<webc-config,Конфигурация {wc}а>>. Для этого на сервере с установленным Р7 необходимо установить самоподписанный сертификат.
. Создать сертификат можно при помощи утилиты https://slproweb.com/products/Win32OpenSSL.html[OpenSSL]. Запустите Win64 OpenSSL Command Prompt от имени администратора, перейдите в директорию, в которой располагается файл `r7-cert.pfx`
. Выполните команду:
+
[source,bash]
----
openssl req -x509 -newkey rsa:2048 -keyout test.key -nodes -out test.crt -subj "/CN=r7.domain.com <.>
----
<.> Вместо `r7.domain.com` укажите имя сервера с установленным Р7.
+
. Установите сертификат в системе на сервере {wc}, поместив его в папку `/usr/local/share/ca-certificates/`, после чего необходимо будет выполнить команду:
+
 sudo update-ca-certificates -v -f.
+
. После установки сертификата переключите Р7 на использование HTTPS с созданным сертификатом согласно https https://support.r7-office.ru/document_server/install-document_server/document_server_linux/https_ds/[официальной инструкции на сайте Р7].
. <<webc-config,Переведите>> {wc} на использование HTTPS.
// +
// [NOTE]
// ====
// Чтобы избежать ошибки с сертификатом на пользовательских машинах, потребуется либо локально установить сгенерированный сертификат, либо перейти на URL сервера документов, например, `\https://r7team.com:8083/` и там выбрать перейти на сайт.
// ====

[#webc-config]
== Конфигурация {wc}а

Для использования Р7-Офис с целью повышения безопасности настоятельно рекомендуется перевести {wc} на использование HTTPS. Если переводить {wc} на использование HTTPS не планируется, перейдите сразу к <<address,указанию адреса>> Р7 Сервера документов в конфигурационном файле {wc}а.

. Создайте самоподписанный сертификат при помощи утилиты https://slproweb.com/products/Win32OpenSSL.html[OpenSSL]:
+
 openssl req -x509 -newkey rsa:4096 -sha256 -keyout .\out\cert.key -out .\out\certificate.crt -subj "/CN=http://WebClientDomain.com" -days 600
+
. Откройте конфигурационный файл {wc}а по адресу `{webconfig}` в любом текстовом редакторе и отредактируйте следующие параметры:
+
[source,json]
----
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "https://*:5004", <.>
        "Certificate": {
        "Path": "/path/to/your.crt", <.>
        "KeyPath": "/path/to/your.key" <.>
      }
    }
  }
----
<.> Адрес, по которому будет доступен {wc}.
<.> Путь к сертификату.
<.> Путь к закрытому ключу сертификата.
+
. [[address]]Следующим шагом в том же конфигурационном файле необходимо указать адрес сервера документов Р7 и определить режим предварительного просмотра. В {of-mc} перейдите на страницу menu:Серверы[Имя-сервера > {wc}], перейдите к разделу menu:Работа с файлами[Настройка Р7-Офис] и отредактируйте следующие параметры:
+
--
NOTE: Для корректной работы предварительного просмотра убедитесь, что URL сервера документов Р7-Офис/OnlyOffice доступен с клиентских рабочих мест.

* _Адрес сервера документов Р7-Офис/OnlyOffice_ -- URL сервера документов Р7-Офис/OnlyOffice. Если URL сервера документов Р7 не указан, остальные настройки будет проигнорированы.

* _Каталог загрузки консолидируемых файлов_ -- каталог на сервере Р7-Офис, в который временно будут загружаться консолидируемые файлы.
--
+
. Откройте в браузере адрес Р7-Офис сервер документов, например, `\https://dvserver.preview.com`.
. Откройте карточку с приложенным файлом. Предпросмотр должен отображаться.

[#auth-token]
== Авторизация с помощью токена

Работа с Р7-Офис сервер документов для консолидации и предварительного просмотра поддерживает авторизацию с помощью токена, что является более безопасным вариантом стандартного режима работы.

.Чтобы настроить авторизацию с помощью токена:
. В конфигурационном файле Р7-Офис по адресу `/etc/r7-office/documentserver/local.json` установите параметры `inbox`, `outbox` и `browser` в значение `true` для использования токенов.
. В том же конфигурационном фйле `local.json` укажите секретное слово для параметров `inbox`, `outbox`, `session`, используя цифры и буквы латинского алфавита, фрагмент конфигурационного файла см. ниже.
+
[source,json]
----
  "services": {
    "CoAuthoring": {
      "sql": {
        "type": "postgres",
        "dbHost": "localhost",
        "dbPort": "5432",
        "dbName": "r7office",
        "dbUser": "r7office",
        "dbPass": "r7office"
      },
      "redis": {
        "host": "localhost"
      },
      "token": {
        "enable": {
          "request": {
            "inbox": true,
            "outbox": true
          },
          "browser": true
        },
        "inbox": {
          "header": "Authorization"
        },
        "outbox": {
          "header": "Authorization"
        }
      },
      "secret": {
        "inbox": {
          "string": "verysecretstring" <.>
        },
        "outbox": {
          "string": "verysecretstring" <.>
        },
        "session": {
          "string": "verysecretstring" <.>
        }
      }
    }
  },
----
<.> Секретное слово для параметра `inbox`.
<.> Секретное слово для параметра `outbox`.
<.> Секретное слово для параметра `session`.
+
. Перезапустите сервер документов Р7.
. В {of-mc}, на странице menu:Серверы[Имя-сервера > {wc}], перейдите к разделу menu:Работа с файлами[Настройка Р7-Офис] и укажите значением секретного слова в параметре _Секретное слово_.
. Перезапустите *{wcs-new}*.
. Если предыдущие шаги настройки выполнены корректно, Р7-Офис сервер документов должен работать без ошибок. Если при предварительном просмотре или консолидации возникают ошибки с упоминанием токена в тексте ошибки, настройка выполнена некорректно, проверьте правильность выполнения описанных выше шагов.
