= Группа настроек "Работа с файлами"

Группа настроек "Работа с файлами" содержит параметры, регулирующие размер прикладываемых файлов, размер карточки, настройки предпросмотра и другие.

Разрешённые для добавления файлы::
По умолчанию пользователь может добавлять в карточки файлы со следующими расширениями:
+
include::webclient:user:partial$extensions.adoc[tags=long-ppt]
+
Администратор может добавить в список новые расширения файлов или удалить существующие путём редактирования параметр в конфигурационном файле. Если параметр отсутствует, создайте его самостоятельно. Новые расширения файлов нужно добавлять через символ `|`.

Максимальный размер прикладываемого файла, байт::
В {wc}е по умолчанию действует ограничение, влияющее на возможность прикладывания файлов большого размера. Максимальный размер файла, прикладываемого при создании карточки.
+
Администратор системы может изменить действующее ограничение, установив размера единичного файла в байтах, не превышающий `2147483647`.

Максимальный размер карточки::
Ограничение для максимального размера тела http-запроса. По умолчанию значение приблизительно равняется `28600000` байт (28,6 Мб). При необходимости ограничить сетевой запрос администратор может указать новое значение, не превышающее `4294967295` байт (4294.97 Мб).

Максимальный размер файлов для предпросмотра, байт::
В {wc}е по умолчанию действует ограничение предпросмотра файлов больше `100` Мб. Увеличение значения повысит нагрузку на сервер и время открытия файла на предпросмотр. Администратор системы может изменить действующее ограничение. Значение указывается в байтах.

Компонент для предпросмотра::
Параметр управляет возможностью предварительного просмотра.

.Доступные варианты:
* Предпросмотр отключен -- предпросмотр файлов в {wc}е будет недоступен.
* Предпросмотр с помощью Р7 -- для предпросмотра будет использоваться компонент "Р7-Офис".

[#r7-office]
== Настройка Р7-Офис

"Р7-Офис. Сервер документов"/OnlyOffice расширяет стандартную функциональность, позволяя отображать документ напрямую и копировать данные непосредственно из файла.

Адрес сервера документов Р7-Офис/OnlyOffice::
URL сервера документов Р7-Офис/OnlyOffice. Если URL сервера документов Р7 не указан, остальные настройки будет проигнорированы.

Каталог загрузки консолидируемых файлов::
Каталог на сервере Р7-Офис, в который временно будут загружаться консолидируемые файлы.

Секретное слово::
Работа с Р7-Офис сервер документов для консолидации и предварительного просмотра поддерживает авторизацию с помощью токена, что является более безопасным вариантом стандартного режима работы. Чтобы настроить авторизацию с помощью токена, укажите секретное слово для использования Р7-Офис. Допускается указывать используя только цифры и буквы латинского алфавита.

Настройка Р7-Офис при помощи {of-mc} подробно описана на странице "xref:webclient-r7.adoc[]".
