= Группа настроек "Подключение к серверу приложений"

Данный раздел документации {of-mc} описывает группу настроек подключения {wc}а к серверу приложений.

Подключение к серверу приложений настраивается в {of-mc} на странице menu:Серверы[Имя-сервера > Web-клиент > Подключение к серверу приложений]. Интерфейс страницы настроек {wc}а представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования. Если компонент редактирования отсутствует, для настройки отображается поле ввода текста.

В шапке страницы расположены кнопки *Отменить* и *Применить*. При нажатии *Применить* отображается сообщение `Изменения на данной странице, вступят в силу после перезапуска службы *{wcs-new}*`. Все настройки сохраняются в Сервисе настроек после перезапуска службы *{wcs-new}*.

При нажатии *Отменить* отменяются все сделанные пользователем изменения.

Конфигурация сервера приложений::
Полный или сокращенный адрес сервера приложений {dv}, к которому подключается {wc} в формате `\https://dvserver.domain.com:port`.

База данных::
База данных для работы с {wc}ом. Если поле не заполнено, используется база по умолчанию.
+
[NOTE]
====
После добавления новой БД необходимо её настроить. Потребуется проверить локализации, импортировать решения и настроить виды карточек по умолчанию.
====

Имя пользователя::
Имя системной учётной записи {dv} в формате `user@domain.com`.

Пароль::
Пароль системной учётной записи.

Таймаут подключения, мс::
Максимальное время ожидания ответа от сервера {dv}.

include::appserver-access.adoc[tags=catalog]
