= Группа настроек "Журналирование"

Адрес журнала операций {wc}а::
Путь к файлу журнала {wc}а (сервиса _{wcs-new}_).

Включить журнал событий навигации::
По умолчанию протоколирование событий навигации отключено. Администратор может включить ведение журнала для записи информации о событиях и последующего анализа ошибок при помощи данного флага. В лог браузера записывается информация о специальных навигационных обработчиках, передаваемым им параметрах и результатах их работы.

Логирование сообщений браузера::
Отправлять сообщения браузера в журнал операций {wc}а. По умолчанию отправка сообщения браузера в журнал операций отключена. Администратор может включить отправку при помощи данного флага.

[#rules]
== Уровни логирования

Категория "Default"::
Глубина фиксации процессов в журнале Web-клиента для категории "Default".
+
* Все (значение по умолчанию)
* Отладка
* Информация
* Предупреждения
* Ошибки

Категория "Microsoft"::
Глубина фиксации процессов в журнале Web-клиента для категории "Microsoft".
+
* Все
* Отладка
* Информация
* Предупреждения (значение по умолчанию)
* Ошибки

Категория "Microsoft.Hosting.Lifetime"::
Глубина фиксации процессов в журнале Web-клиента для категории "Microsoft.Hosting.Lifetime".
+
* Все
* Отладка
* Информация (значение по умолчанию)
* Предупреждения
* Ошибки
