= Группа настроек "Сайт"

[#pechenkies]
== Пользовательские cookie

Интервал автоматического обновления сессии, ч::
Настройка позволяет продлевать срок уже выданных cookie, если пользователь зашёл до того, как они истекли.
+
По умолчанию настройка отключена, то есть установлена в значение `0`. Можно задать количество часов.
+
Когда пользователь авторизуется в {wc}е, ему по умолчанию выдаются cookie на 5 дней. Если в настройке указано значение `24` часа, действие cookie будет продлено, когда пользователь откроет {wc}. Настройка сработает только если пользователь откроет {wc} в промежутке между указанным временем и сроком истечения сессии.

Период действия пользовательской сессии, ч::
Настройка устанавливает период действия пользовательской сессии. Значение по умолчанию: `120` часов (5 дней).

Период действия пользовательской сессии на мобильных устройствах, ч::
Настройка отдельно задаёт период действия пользовательской сессии на мобильных устройствах. Значение по умолчанию: `120` часов (5 дней).

Настройки можно комбинировать. Например, задать _Период действия пользовательской сессии_ в значение `240` часов, чтобы все пользователи получали cookie на 10 дней. Для _мобильных устройств_ можно указать период в `720` часов (30 дней). А также установить _Интервал автоматического обновления_ на `72` часа. Когда пользователь откроет {wc} по прошествии трёх дней с предыдущей авторизации, cookie автоматически будут продлены.

[#devices]
== Устройства

Пользовательский интерфейс {wc}а адаптируется под тип клиентского устройства, который определяется по https://ru.wikipedia.org/wiki/User_Agent[User Agent], передаваемому веб-браузером клиента. Если User Agent не сопоставляется или некорректно сопоставляется с типом устройства, нужно изменить шаблон, по которому выполняется сопоставление:

Новые мобильные устройства::
Шаблон определения мобильных устройств нового поколения

Старые мобильные устройства::
Шаблон определения старых мобильных устройств

Планшеты::
Шаблон определения планшетов
