:what-service: {wcs-new}

= Страница "{wc}"

Настройки {wc}а аналогичны тем, что доступны в _Панели управления {wc}ом_ для ОС Windows. Структура настроек на странице частично соответствует аналогичной в _Панели управления_.

NOTE: Все описанные настройки хранятся в Сервисе настроек и могут также дублироваться в конфигурационном файле модуля или консоли. Настройки в конфигурационных файлах имеют приоритет по сравнению с настройками в Сервисе настроек. Если настройка отсутствует в конфигурационном файле, но присутствует в Сервисе настроек, она будет получена из Сервиса настроек.

include::partial$excerpts.adoc[tags=address]

При запуске {wc} в сервисе настроек регистрируются или обновляются следующие данные:

* Имя сервера
* Операционная система
* Версия ОС
* Данные об установленном компоненте {wc}:
** Системное название модуля
** Продуктовая версия модуля
** Номер сборки модуля

WARNING: Перед запуском службы убедитесь, что в конфигурационном файле модуля {wf} указаны параметры menu:ServiceId[], menu:SettingsService[ConnectionString] и menu:SettingsService[ApiKey], подробнее см. в разделе "xref:workflow:admin:install.adoc[]".

Интерфейс страницы настроек {wc}а представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования. Если компонент редактирования отсутствует, для настройки отображается поле ввода текста.

В шапке страницы расположены кнопки *Отменить* и *Применить*. При нажатии *Применить* отображается сообщение `Изменения на данной странице, вступят в силу после перезапуска службы *{wcs-new}*`. Все настройки сохраняются в Сервисе настроек после перезапуска службы *{wcs-new}*.

При нажатии *Отменить* отменяются все сделанные пользователем изменения.

[#connection]
== Подключение

Настройки подключения {wc}а к серверу приложений, включая адрес сервера приложений, базу данных для работы с {wc}ом и другие параметры, необходимые для подключения к серверу {dv}.

См. подробнее в разделе "xref:webclient-connection.adoc[]".

[#solutions]
== Решения

Раздел _Решения_ содержит инструменты импорта решений с разметками карточек, включая импорт решений, импорт стандартных решений и удаление решений для каждой БД, подключенной к {wc}у.

См. подробнее в разделе "xref:webclient-solutions.adoc[]".

[#locales]
== Локализации

Список доступных языков и выбранный по умолчанию язык, настройка языков локализации, доступных в {wc}е и программе {kvr}.

См. подробнее в разделе "xref:webclient-locales.adoc[]".

[#kinds]
== Виды карточек

Элементы в группе настроек предназначены для настройки видов карточек, с которыми по умолчанию будут создаваться новые карточки соответствующих типов.

См. подробнее в разделе "xref:webclient-kinds.adoc[]".

[#interface]
== Интерфейс

Настройки в данной группе регулируют внешний вид и поведение элементов интерфейса главной страницы модуля.

См. подробнее в разделе "xref:webclient-interface.adoc[]".

[#site]
== Сайт

Общие настройки интерфейса, адаптивности и времени жизни пользовательских сессий.

См. подробнее в разделе "xref:webclient-site.adoc[]".

[#performance]
== Производительность

Настройки для управления таймером закрытия пользовательских сессий, параметры счётчика непрочитанных карточек и кэширования справочников.

См. подробнее в разделе "xref:webclient-performance.adoc[]".

[#files]
== Работа с файлами

Группа настроек "Работа с файлами" содержит параметры, регулирующие размер прикладываемых файлов, размер карточки, настройки предпросмотра и другие.

См. подробнее в разделе "xref:webclient-files.adoc[]".

[#tools]
== Инструменты

Группа настроек "Инструменты" содержит параметры _DVWebTool_ и _DVSupService_.

См. подробнее в разделе "xref:webclient-tools.adoc[]".

[#signature]
== Электронная подпись

Группа настроек "Электронная подпись" содержит параметры, связанные с конфигурацией электронной подписи.

См. подробнее в разделе "xref:webclient-signature.adoc[]".

[#logging]
== Журналирование

Параметры журналирования компонентов {wc}а, включая журнал событий навигации и уровни логирования.

См. подробнее в разделе "xref:webclient-logging.adoc[]".
