= Страница "{wc}"

Настройки {wc}а дублируют аналогичные в _Панели управления {wc}ом_ для ОС Windows. Структура настроек на странице частично соответствует аналогичной в _Панели управления_.

NOTE: Все описанные настройки хранятся в Сервисе настроек и могут также дублироваться в конфигурационном файле модуля или консоли. Настройки в конфигурационных файлах имеют приоритет по сравнению с настройками в Сервисе настроек. Если настройка отсутствует в конфигурационном файле, но присутствует в Сервисе настроек, она будет получена из Сервиса настроек.

Интерфейс страницы настроек {wc}а представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования. Если компонент редактирования отсутствует, для настройки отображается поле ввода текста.

В шапке страницы расположены кнопки *Отменить* и *Применить*. При нажатии *Применить* отображается сообщение `Изменения на данной странице, вступят в силу после перезапуска службы *{sss-new}*`. Все настройки сохраняются в Сервисе настроек после перезапуска службы *{wcs-new}*.

При нажатии *Отменить* отменяются все сделанные пользователем изменения.