:what-service: {wfs-new}

= Страница "{wf}"

Настройки {wf} аналогичны тем, что доступны в _Панели управления {wc}ом_ для ОС Windows. Структура настроек на странице частично соответствует аналогичной в _Панели управления_.

NOTE: Все описанные настройки хранятся в Сервисе настроек и могут также дублироваться в конфигурационном файле модуля или консоли. Настройки в конфигурационных файлах имеют приоритет по сравнению с настройками в Сервисе настроек. Если настройка отсутствует в конфигурационном файле, но присутствует в Сервисе настроек, она будет получена из Сервиса настроек.

include::partial$excerpts.adoc[tags=address]

При запуске службы модуля {wf} в сервисе настроек регистрируются или обновляются следующие данные:

* Имя сервера
* Операционная система
* Версия ОС
* Данные об установленном компоненте СУБП:
** Системное название модуля
** Продуктовая версия модуля
** Номер сборки модуля

Интерфейс страницы настроек модуля {wf} представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования. Если компонент редактирования отсутствует, для настройки отображается поле ввода текста.

В шапке страницы расположены кнопки *Отменить* и *Применить*. При нажатии *Применить* отображается сообщение `Изменения на данной странице, вступят в силу после перезапуска службы *{wfs-new}*`. Все настройки сохраняются в Сервисе настроек после перезапуска службы *{wfs-new}*.

При нажатии *Отменить* отменяются все сделанные пользователем изменения.
