= Предоставление доступа к {of-mc}

При работе с Консолью управления выделяется единственная роль -- _Администратор {of-mc}_. Администратору предоставляется полный доступ ко всем функциям модуля.

Администратором считается пользователь, xref:install.adoc[установивший] {mc}, а также любой пользователь, включённый в группу *{dv-web-admin-cns-admins-serv}* на компьютере с модулем {wac}. Пользователи, входящие в эту группу, имеют право работать с Консолью управления {dv}.

Ещё одна группа -- *{dv-sett-serv-admins-serv}*. Пользователи, входящие в эту группу, имеют право менять настройки в _{sett-serv}_.

При установке модуля группы создаются автоматически.
include::install.adoc[tags=nets]
Предоставить другим пользователям доступ к консоли или изменению настроек в _{sett-serv}_ можно вручную.

.Чтобы предоставить доступ к модулю и/или _{to-sett-serv}_:
. Включите пользователя в локальные группы безопасности *{dv-web-admin-cns-admins-serv}* и/или *{dv-sett-serv-admins-serv}* на компьютере с модулем {wac}.
. Также включите пользователя в группу безопасности *{dv-web-admin-cns-admins-serv}* на сервере {dv}, чтобы была возможность открыть карточку из модулей _{wc}_ и _{wincl}_.
. Выйдите и повторно войдите в учётную запись Windows, чтобы применить новые права.

При обращении к приложению всегда срабатывает Windows аутентификация с проверкой того, что пользователь находится в группе *{dv-web-admin-cns-admins-serv}*. Если пользователь не входит в группу, выводится окно с сообщением об ошибке: `Работа с "{mc}" разрешена только пользователям локальной группы *{dv-web-admin-cns-admins-serv}*`.
