= Предоставление доступа к {of-mc}

При работе с Консолью управления выделяется роль _Администратор {of-mc}_. Администратору предоставляется полный доступ ко всем функциям модуля.

// Администратором считается пользователь, xref:install-server.adoc[установивший] {mc}, а также любой пользователь, включённый в группу *{dv-web-admin-cns-admins-serv}* на компьютере с модулем {mc}. Пользователи, входящие в эту группу, имеют право работать с Консолью управления {dv}.

// Пользователи, входящие в группу *{dv-sett-serv-admins-serv}*, имеют право менять настройки в _{sett-serv}_.

// {mc} по умолчанию запускает {wacss-new} под учётной записью Network Service, которая включается в группы *{dv-sett-serv-admins-serv}* и *{dv-web-admin-cns-admins-serv}* автоматически.

Предоставить пользователям доступ к консоли или изменению настроек в _{sett-serv}_ можно вручную, изменив конфигурационный файл:

----
  "Groups": {
    "Docsvision Management Console Administrators": [
      "account@domain.com" <.>
    ]
  }
----
<.> Добавьте пользователей, которые должны иметь доступ к {of-mc}.

// .Чтобы предоставить доступ к модулю и/или "{to-sett-serv}":
// . Включите пользователя в локальные группы безопасности *{dv-web-admin-cns-admins-serv}* и/или *{dv-sett-serv-admins-serv}* на компьютере с модулем {mc}.
// . Также включите пользователя в группу безопасности *{dv-web-admin-cns-admins-serv}* на сервере {dv}, чтобы была возможность открыть карточку из модулей _{wc}_ и _{wincl}_.
// . Выйдите и повторно войдите в учётную запись Windows, чтобы применить новые права.
//
// При обращении к приложению всегда срабатывает проверка принадлежности пользователя к группе *{dv-web-admin-cns-admins-serv}*. Если пользователь не входит в группу, выводится окно с сообщением об ошибке: `Работа с "{mc}" разрешена только пользователям локальной группы *{dv-web-admin-cns-admins-serv}*`.
//
// .Обратите внимание!
// ****
// Группы настраиваются в конфигурационном файле модуля _{pl}_. Структура файла подробно описана в документации модуля _{pl}_, раздел "xref:6.1@platform:admin:config-platform.adoc[]".
// ****

****
Сервер {dv}, установленный на Linux, требует создание keytab-файла.

// tag::keytab[]
Файл выпускается специальной командой `ktpass`, как правило, в Windows средеfootnote:[В Linux keytab-файл создаётся при вводе сервера в домен. Подробная информация о вводе в домен приведена https://wiki.astralinux.ru/pages/viewpage.action?pageId=27361515[в документации Astra Linux]]).

.Пример команды для создания keytab-файла
====
 ktpass -princ HTTP/server.example.com@EXAMPLE.COM -mapuser administrator@example.com -crypto RC4-HMAC-NT -ptype KRB5_NT_PRINCIPAL -pass Password -out C:\\\dvapp.keytab
====

Сгенерированный `krb5.keytab` файл необходимо поместить в каталог `/etc/` на сервере Linux.
// end::keytab[]

Для запуска {of-mc}, в связи с особенностями протокола аутентификации Kerberos, необходимо вводить адрес {mc} в браузере с доменным именем. При обращении к сайту по IP войти в Консоль не удастся.
****
