= Предоставление доступа к {of-mc}

При работе с Консолью управления выделяется роль _Администратор {of-mc}_. Администратору предоставляется полный доступ ко всем функциям модуля.

// Администратором считается пользователь, xref:install-server.adoc[установивший] {mc}, а также любой пользователь, включённый в группу *{dv-web-admin-cns-admins-serv}* на компьютере с модулем {mc}. Пользователи, входящие в эту группу, имеют право работать с Консолью управления {dv}.

// Пользователи, входящие в группу *{dv-sett-serv-admins-serv}*, имеют право менять настройки в _{sett-serv}_.

// {mc} по умолчанию запускает {wacss-new} под учётной записью Network Service, которая включается в группы *{dv-sett-serv-admins-serv}* и *{dv-web-admin-cns-admins-serv}* автоматически.

Предоставить пользователям доступ к консоли или изменению настроек в _{sett-serv}_ можно вручную, изменив конфигурационный файл:

----
  "Groups": {
    "Docsvision Management Console Administrators": [
      "account@domain.com" <.>
    ]
  }
----
<.> Добавьте пользователей, которые должны иметь доступ к {of-mc}.

// .Чтобы предоставить доступ к модулю и/или "{to-sett-serv}":
// . Включите пользователя в локальные группы безопасности *{dv-web-admin-cns-admins-serv}* и/или *{dv-sett-serv-admins-serv}* на компьютере с модулем {mc}.
// . Также включите пользователя в группу безопасности *{dv-web-admin-cns-admins-serv}* на сервере {dv}, чтобы была возможность открыть карточку из модулей _{wc}_ и _{wincl}_.
// . Выйдите и повторно войдите в учётную запись Windows, чтобы применить новые права.
//
// При обращении к приложению всегда срабатывает проверка принадлежности пользователя к группе *{dv-web-admin-cns-admins-serv}*. Если пользователь не входит в группу, выводится окно с сообщением об ошибке: `Работа с "{mc}" разрешена только пользователям локальной группы *{dv-web-admin-cns-admins-serv}*`.
//
// .Обратите внимание!
// ****
// Группы настраиваются в конфигурационном файле модуля _{pl}_. Структура файла подробно описана в документации модуля _{pl}_, раздел "xref:6.1@platform:admin:config-platform.adoc[]".
// ****

****
Сервер {dv}, установленный на Linux, требует создание keytab-файла.

// tag::keytab[]
Файл выпускается специальной командой `ktpass`, как правило, в Windows средеfootnote:[В Linux keytab-файл создаётся при вводе сервера в домен. Подробная информация о вводе в домен приведена https://wiki.astralinux.ru/pages/viewpage.action?pageId=27361515[в документации Astra Linux]].

.Пример команды для создания keytab-файла
====
 ktpass -princ HTTP/server.example.com@EXAMPLE.COM -mapuser administrator@example.com -crypto RC4-HMAC-NT -ptype KRB5_NT_PRINCIPAL -pass Password -out C:\\\krb5.keytab
====

Сгенерированный `krb5.keytab` файл необходимо поместить в каталог `/etc/` на сервере Linux.
// end::keytab[]

Для запуска {of-mc}, в связи с особенностями протокола аутентификации Kerberos, необходимо вводить адрес {mc} в браузере с доменным именем. При обращении к сайту по IP войти в Консоль не удастся.
****

[#domain]
== Настройка работы в домене

{mc} поддерживает работу в одном или нескольких доменах. Для этого в конфигурационном файле модуля необходимо выполнить настройку доменных каталогов -- параметр `"Catalogs"`:

В конфигурационном файле настройка представлена следующим массивом: `"Catalogs": []`. Настройки вступают в работу, если в массиве присутствует хотя бы одно описание каталога.

[source,json]
----
 "Catalogs": [
  {
   "FullDomainName": "example1.com", <.>
    "NetBiosDomainName": "example1", <.>
    "LdapOptions": { <.>
      "LdapServerAddresses": [ "example1.com" ], <.>
      "AuthType": "Basic", <.>
      "Credential": { <.>
        "UserName": "user@example1.com",
        "Password": "Password"
      }
    }
 },
  {
    "FullDomainName": "example2.com", <.>
    "ChallengeTo": "example1.com" <.>
  }
],
----
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `NetBiosDomainName` -- `NetBios`-имя домена указывается в формате `domain\\user` перед `\\`.
<.> `LdapOptions` -- настройки подключения к LDAP каталогу домена.
<.> `LdapServerAddresses` -- адреса серверов LDAP данного домена. Если адрес соответствует полному имени домену, параметр можно удалить.
<.> `AuthType` -- тип аутентификации в LDAP.
<.> `Credential` -- логин и пароль пользователя для подключения к LDAP-каталогам текущего домена. Пароль для подключения можно зашифровать, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `ChallengeTo` -- настройка позволяет переадресовывать запросы от выбранного домена к каталогам указанного домена, см. <<challengeto,далее>>.

.Раздел `Catalogs` может содержать массив настроек вида:
[source,json]
----
 {
    "FullDomainName": "example.com", <.>
    "NetBiosDomainName": "EXAMPLE", <.>
    "LdapOptions": { <.>
      "LdapServerAddresses": [ "example.com" ], <.>
      "AuthType": "Basic", <.>
      "Port": 389, <.>
      "Credential": { <.>
        "UserName": "user@example.com",
        "Password": "Password"
      }
    }
}
----
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `NetBiosDomainName` -- `NetBios`-имя домена указывается в формате `domain\\user` перед `\\`.
<.> `LdapOptions` -- настройки подключения к LDAP каталогу домена.
<.> `LdapServerAddresses` -- адреса серверов LDAP данного домена. Если адрес соответствует полному имени домену, параметр можно удалить.
<.> `AuthType` -- тип аутентификации в LDAP.
<.> `Port` -- порт подключения к LDAP каталогам, перечисленным в `LdapServerAddresses`.
<.> `Credential` -- логин и пароль пользователя для подключения к LDAP-каталогам текущего домена. Пароль для подключения можно зашифровать, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".

include::6.1@platform:admin:config-domains.adoc[tags=chalto]
