= Предоставление доступа к Консоли управления

При работе с Консолью управления выделяется единственная роль -- _Администратор консоли управления_. Администратору предоставляется полный доступ ко всем функциям модуля.

Администратором считается пользователь, xref:installation.adoc[установивший] Консоль управления, а также любой пользователь, включённый в группу *{wacs}* на компьютере с модулем {wac}. Пользователи, входящие в эту группу, имеют право работать с Консолью управления {dv}.

Ещё одна группа -- *{wacss}*. Пользователи, входящие в эту группу, имеют право менять настройки в хранилище настроек.

При установке модуля группы создаются автоматически. Предоставить пользователям доступ к консоли или изменению настроек в хранилище настроек можно вручную.

.Чтобы предоставить доступ к модулю и/или хранилищу настроек:
. Включите пользователя в локальные группы безопасности *{wacs}* и/или *{wacss}* на компьютере с модулем {wac}.
. Выйдите и повторно войдите в учётную запись Windows, чтобы применить новые права.

При обращении к приложению всегда срабатывает Windows аутентификация с проверкой того, что пользователь находится в группе *{wacs}*. Если пользователь не входит в группу, выводится окно с сообщением об ошибке: `Работа с "Консоль управления Docsvision" разрешена только пользователям локальной группы *{wacs}*`.
