= Предоставление доступа к Консоли управления

При работе с Консолью управления выделяется единственная роль -- _Администратор консоли управления_. Администратору предоставляется полный доступ ко всем функциям модуля.

Администратором считается пользователь, xref:install.adoc[установивший] Консоль управления, а также любой пользователь, включённый в группу *{wacs-g}* на компьютере с модулем {wac}. Пользователи, входящие в эту группу, имеют право работать с Консолью управления {dv}.

Ещё одна группа -- *{wacss-g}*. Пользователи, входящие в эту группу, имеют право менять настройки в хранилище настроек.

При установке модуля группы создаются автоматически.
include::install.adoc[tags=nets]
Предоставить другим пользователям доступ к консоли или изменению настроек в хранилище настроек можно вручную.

.Чтобы предоставить доступ к модулю и/или хранилищу настроек:
. Включите пользователя в локальные группы безопасности *{wacs-g}* и/или *{wacss-g}* на компьютере с модулем {wac}.
. Выйдите и повторно войдите в учётную запись Windows, чтобы применить новые права.

При обращении к приложению всегда срабатывает Windows аутентификация с проверкой того, что пользователь находится в группе *{wacs-g}*. Если пользователь не входит в группу, выводится окно с сообщением об ошибке: `Работа с "Консоль управления Docsvision" разрешена только пользователям локальной группы *{wacs-g}*`.
