= Настройки подключения к {to-sett-serv}

Адрес сервиса настроек берется из конфигурационного файла модуля {mc} `appsettings.json`. Поддерживается единственный способ инсталляции, когда {mc} и _{sett-serv}_ устанавливаются на один сервер.

В таком случае адрес хранилища автоматически записывается в конфигурационный файл во время установки модуля.

При обращении к _{to-sett-serv}_, {mc} записывает в хранилище файл с настройками для BackOffice по умолчанию. Данные настройки недоступны для изменения. В файле также содержатся типы подключений в зависимости от конфигураций.

После запуска Службы {ws} {mc} читает из _{of-sett-serv}_ информацию о Службе {ws} и её расширениях, затем добавляет новый узел на вкладку "xref:user:worker.adoc[Служба {ws}]" на странице настроек {of-mc}.

Администратор добавляет процесс на узел Службы {ws}, указывая тип конфигурации. Тип конфигурации доступен только из тех расширений, с которыми работает данная служба {ws}.

WARNING: Для корректной работы {of-mc} со Службой {ws} необходимо, чтобы учётная запись, под которой запускается Служба {ws} была включена в группу *{dv-sett-serv-admins-serv}* на сервере {dv}. В противном случае будет недоступен xref:user:worker.adoc[узел Службы {ws}].
