= Настройки подключения к Хранилищу настроек

Адрес сервиса настроек берется из конфигурационного файла модуля {wac} в формате `.json`. Поддерживается единственный способ инсталляции, когда Консоль управления и _Хранилище настроек_ устанавливаются на один сервер.

В таком случае адрес хранилища автоматически записывается в конфигурационный файл во время установки модуля.

При обращении к _Хранилищу настроек_, {wac} записывает в хранилище файл с настройками для BackOffice по умолчанию. Данные настройки недоступны для изменения. В файле, в том числе, содержатся типы подключений в зависимости от конфигураций.

После запуска Службы {ws}, Консоль управления читает из _Хранилища настроек_ информацию о Службе {ws} и её расширениях, затем добавляет новый узел на вкладку xref:user:worker.adoc["Служба {ws}"] на странице настроек Консоли управления.

Администратор добавляет процесс на узел Службы {ws}, указывая тип конфигурации. Тип конфигурации доступен только из тех расширений, с которыми работает данная служба {ws}.
