= Аннотация

== Назначение документа

Настоящий документ является руководством пользователя модуля {dv} 5. Консоль управления {dv} (далее -- Консоль управления, Модуль).

Документ содержит инструкцию по работе в Консоли управления: приведен список решаемых задач, описание пользовательского интерфейса, инструкция по использованию.

Инструкция по установке и первоначальной настройке Модуля приведена в Руководстве администратора.

Документ предназначен для администраторов {dv}.

== Как организован документ

Настоящее руководство содержит следующие разделы:



== Соглашения по оформлению

* *Жирный* -- используется при написании названий элементов экранного интерфейса и выделения *важной информации*;
* _Курсив_ -- используется для обозначения новых терминов, названий типов и видов карточек;
* http://{dv}.com[Синий] -- используется для выделения перекрестных ссылок внутри документа и ссылок на доступные внешние документы, для указания адресов интернет-страниц;
* `Моноширинный` -- используется для выделения текстов макрокоманд и программных кодов, имен файлов и путей к ним.