= Аннотация

== Назначение документа

Настоящий документ является руководством пользователя модуля «Docsvision 5. Консоль управления Docsvision» (далее – «Консоль управления», «Модуль»).

Документ содержит инструкцию по работе в Консоли управления: приведен список решаемых задач, описание пользовательского интерфейса, инструкция по использованию.

Инструкция по установке и первоначальной настройке Модуля приведена в Руководстве администратора.

Документ предназначен для администраторов Docsvision.

== Как организован документ

Настоящее руководство содержит следующие разделы:

. xref:Introduction.adoc[Введение] (приведено краткое описание возможностей Модуля, указаны требования к пользователям).
. xref:PurposeAndConditions.adoc[Назначение и условия применения] (указана цель автоматизации, приведены требования к компьютеру пользователя Консоли настройки).
. xref:PrepareToWork.adoc[Подготовка к работе] (указаны предварительные действия).
. xref:UserInterface.adoc[Интерфейс пользователя](приведено описание пользовательского интерфейса).
. xref:Operations.adoc[Описание операций] (содержит описание общих операций в Консоли управления, инструкции по настройке подключений (к серверу Docsvision, почтовому серверу и др.), формированию _дашборда_, работе в виджетами и настройке Службы {ws}).
. xref:Exceptions.adoc[Сообщения об ошибках] (перечислены возможные ошибки при работе с Консолью управления и пути их решения).

== Соглашения по оформлению

* *Жирный* – используется при написании названий элементов экранного интерфейса и выделения *важной информации*;
* _Курсив_ – используется для обозначения новых терминов, названий типов и видов карточек;
* http://docsvision.com[Синий] – используется для выделения перекрестных ссылок внутри документа и ссылок на доступные внешние документы, для указания адресов интернет-страниц;
* `Моноширинный` – используется для выделения текстов макрокоманд и программных кодов, имен файлов и путей к ним.