= Страница "Настройки сервера"

Настройки сервера заменяют аналогичные в программе "{cns}" для ОС Windows. Структура настроек на странице частично соответствует аналогичной в Консоли настроек.

NOTE: Все описанные настройки хранятся в Сервисе настроек и могут дублироваться в конфигурационных файлах модулей. Настройки в конфигурационном файле имеют приоритет по сравнению с настройками в Сервисе настроек.

Интерфейс страницы настроек Сервера приложений представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования. Если компонент редактирования отсутствует, для настройки отображается поле ввода текста.

В шапке страницы расположены кнопки *Отменить* и *Применить*. При нажатии *Применить* отображается сообщение `Изменения на данной странице, вступят в силу после перезапуска службы *{sss-new}*`. Все настройки сохраняются в Сервисе настроек после перезапуска службы *{sss-new}*.

При нажатии *Отменить* отменяются все сделанные пользователем изменения.

[#general-settings]
== Секция "Общие настройки"

* [[docs-url]]Поле _Адрес сайта документации_. Настройка дополняет конфигурацию через конфигурационный файл модуля {pl}footnote:[Подробнее см. в разделе "xref:platform:console:docs-location.adoc[]".] и поддерживает аналогичные шаблоны расположения документации, предоставляя администратору возможность выполнять настройки через графический интерфейс.
* Кнопка "Восстановить по умолчанию" -- восстанавливает стандартные настройки сервера, сбрасывает значения всех полей на заводские.
* Логин системной учётной записи -- поле для ввода имени системной учётной записи {dv} в формате `user@domain.com`.
* Пароль системной учетной записи -- поле для ввода пароля системной учётной записи {dv}. Рекомендуется хранить в зашифрованном виде. Подробнее про шифрование см. в документации по установке системы, раздел "xref:dev@install-linux:ROOT:appendix/account-protection.adoc[]".
* Штамп сертификата шифрования паролей -- отпечаток закрытого ключа шифрования SHA1. Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:dev@install-linux::appendix/account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно не указывать.
* Имя компьютера в текущем домене Active Directory -- необходимо для указания имени любого компьютера в текущем домене Active Directory. Используется при получении списка доступных членов домена при настройке дискреционной безопасности.
* API-ключ для подключения к Workflow -- API-ключ для подключения серверного расширения {wf}. Главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые.
* Следующие настройки входят в блок _Журналирование_:
** Файл журнала -- путь к файлу журнала, в котором регистрируются выполняемые сервером операции. По умолчанию используется: `/var/log/docsvision/platform/dvappserver.log`.
** Уровень журналирования -- кнопки выбора глубины фиксации процессов в журнале сервера приложений. По умолчанию используется: `Error`.
+
.Доступные варианты:
*** *Отключено* (Off)
*** *Ошибки* (Error)
*** *Предупреждения* (Warning)
*** *Сообщения* (Info)
*** *Подробное* (рналирование / Verbose)
+
* Следующие настройки входят в блок _Модули_:
** Проверка версии БД -- когда флаг установлен, сообщение о несоответствии версии базы данных и версии сервера {dv} вносится в журнал выполняемых сервером операций.
** Проверять версию базы данных -- когда флаг установлен, сообщение о несоответствии версии базы данных и версии сервера {dv} вносится в журнал выполняемых сервером операций.
** Обновление БД -- флаг включает режим установки модулей без загрузки данных в БД. По умолчанию флаг активирован.
** Пропускать обновление БД при установке модулей -- флаг отключает обновление БД при установке модулей. По умолчанию флаг неактивен.
* Следующие настройки входят в блок "Локализация полей":
** Язык -- язык локализации по умолчанию. По умолчанию используется Русский. Чтобы изменить язык локализации по умолчанию, измените значение параметра на: Русский, English. Подробнее см. "xref:dev@platform:console:default-localization.adoc[]".
** Режим локализации полей -- установка локализованных значений для полей клиентского приложения. Подробнее см. "xref:dev@platform:console:default-localization.adoc[]".
+
.Доступные варианты:
*** *Выкл* / Disable
*** *Чтение* / Read
*** *Запись* / Write
*** *Вкл* / Enable
*** *Особый* режим / WriteAlways



