= Test

.Страница представляет собой таблицу со следующими колонками:
* _Дата создания_ -- дата и время, когда сообщение было зарегистрировано. По умолчанию таблица отсортирована по дате создания сообщения.
+
* _Дайджест_ -- сообщение было зарегистрировано для карточки с данным названием в системе {dv}.
+
[#state]
* Состояние -- состояние обработки сообщения:
+
** _Обработано_ -- сообщение было обработано.
** _Не обработано_ -- сообщение ещё не обрабатывалось.
** _Ошибка_ -- обработка сообщения завершилась с ошибкой.
** _Блокировано_ -- при обработке сообщения возникла ошибка, но обработка не завершена. Указывается именно количество сообщений имеющих блокировку, а не количество блокировок.
+
Сообщение может содержать ошибку в любом состоянии, но если сообщение блокировано ошибкой, состояние будет: _Блокировано, ошибка_.
+
Если сообщение было обработано с ошибкой или блокировано, строка сообщения становится кликабельной. Нажмите на такую строку сообщения, чтобы перейти на страницу xref:block-error-log.adoc["Журнала ошибок и блокировок"].
+
[#service]
* _Сервис обработки_ -- {is-ws} Службы {ws}, предназначенная для выполнения определённых задач. Например, сервис обработки Backoffice предназначен для обработки задач, связанных с функционированием модуля _{bo}_, а именно: создание заданий по группе заданий, изменений состояния заданий при выполнении и др.