= Выполняемые функции и задачи

Базовые функции Консоли управления:

* Аутентификация пользователя.

Данная функция решает задачу ограничения доступа пользователей к Консоли управления. Аутентификация выполняется автоматически при подключении пользователя путём проверки вхождения его в ожидаемую группу безопасности (используется встроенная аутентификация Windows).

* Настройка соединений с внешними системами.

Службе Docsvision и её компонентам, настраиваемым с помощью Консоли управления, может требоваться доступ к внешним системам (например, почтовому серверу). Данная задача решается с помощью _соединений_, в которых хранятся параметры подключений к внешним системам.

* Протоколирование операций.

Изменения, выполненные пользователем, должны быть отслеживаемы. Данная задача выполняется с помощью журнала операций, в который протоколируются действия пользователей.

Функции для настройки и мониторинга работы системы Docsvision и её компонентов предоставляются _расширениями_ Модуля:

* Функции расширение для работы с Сервисом рабочих процессов[^1]:
* Настройка конфигурации Сервиса рабочих процессов.

Пользователь может подключать новые экземпляры Сервиса рабочих процессов, добавлять и настраивать _рабочие процессы_.

* Предоставление информации о загрузке Служб рабочих процессов.

Анализ текущего состояния обработки задач подключенными Службами рабочих процессов осуществляется с использованием _виджетов_ с очередями входящих и исходящих сообщений.

* Поиск неисправности в процессах обработки бизнес-задач.

Для анализа причин возникновения нештатных ситуации пользователю предоставляются возможности просматривать сообщения и ошибки, связанные с определённой карточкой.

[^1]: В данном версии входит в состав модуля «Консоль управления Docsvision».