= Выполняемые функции и задачи

Базовые функции Консоли управления:

* Аутентификация пользователя.

Данная функция решает задачу ограничения доступа пользователей к Консоли управления. Аутентификация выполняется автоматически при подключении пользователя путём проверки вхождения его в ожидаемую группу безопасности (используется встроенная аутентификация Windows).

* Настройка соединений с внешними системами.

Службе {dv} и её компонентам, настраиваемым с помощью Консоли управления, может требоваться доступ к внешним системам (например, почтовому серверу). Данная задача решается с помощью _соединений_, в которых хранятся параметры подключений к внешним системам.

* Протоколирование операций.

Изменения, выполненные пользователем, должны быть отслеживаемы. Данная задача выполняется с помощью журнала операций, в который протоколируются действия пользователей.

Функции для настройки и мониторинга работы системы {dv} и её компонентов предоставляются _расширениями_ Модуля:

* Функции расширение для работы с Сервисом {ws}[^1]:
* Настройка конфигурации Сервиса {ws}.

Пользователь может подключать новые экземпляры Сервиса {ws}, добавлять и настраивать _фоновые операции_.

* Предоставление информации о загрузке Служб {ws}.

Анализ текущего состояния обработки задач подключенными Службами {ws} осуществляется с использованием _виджетов_ с очередями входящих и исходящих сообщений.

* Поиск неисправности в процессах обработки бизнес-задач.

Для анализа причин возникновения нештатных ситуации пользователю предоставляются возможности просматривать сообщения и ошибки, связанные с определённой карточкой.

[^1]: В данном версии входит в состав модуля Консоль управления {dv}.