= Изменения в релизной версии

* Сервер {dv}, работающий в ОС Linux, теперь способен получать параметры конфигурации из Сервиса настроек.
* Обновлена стартовая страница настроек {of-mc}, страница настроек соединений, почтового сервера и службы фоновых операций.
* Исходный код {of-mc} был переработан для приведения к системе плагинов, определяющих интерфейс настроек модуля в Консоли и взаимодействие с хранилищем настроек этого модуля.
* Виджеты настройки Службы {ws} в {of-mc} переведены на схему работы через настраиваемые компоненты редактирования.
* Разработаны и поддержаны компоненты редактирования, необходимые для настройки сервера приложений в {of-mc}.
* В Консоли управления добавлена поддержка ввода настроек при отсутствии компонента редактирования. Если компонент редактирования настроек отсутствует, отображается текстовое поле для ввода.
* Для {of-mc} разработана страница, содержащая общие настройки сервера приложений.
* Для {of-mc} разработана страница, содержащая серверы, зарегистрированные в Сервисе настроек.
* Поддержана возможность работы Сервера приложений с Консолью управления. Сервер приложений регистрируется в Сервисе настроек и передаёт данные в хранилище настроек.
* Поддержана возможность прочтения настроек Сервера приложений из {of-mc}.
