= Изменения в релизной версии

* Сервер {dv}, работающий в ОС Linux, теперь способен получать параметры конфигурации из Сервиса настроек.
* Обновлена стартовая страница настроек {of-mc}, страница настроек соединений, почтового сервера и службы фоновых операций.
* Исходный код {of-mc} был переработан для приведения к системе плагинов, определяющих интерфейс настроек модуля в Консоли и взаимодействие с сервисом настроек.
* Виджеты настройки Службы {ws} в {of-mc} переведены на схему работы через настраиваемые компоненты редактирования.
* Поддержана возможность получения настроек Сервера приложений в Сервисе настроек {of-mc}, если адрес Сервиса указан в конфигурационном файле модуля {pl}.
* Разработаны и поддержаны компоненты редактирования, необходимые для настройки сервера приложений в {of-mc}.
* В {of-mc} добавлена поддержка ввода настроек при отсутствии компонента редактирования. Если компонент редактирования настроек отсутствует, отображается текстовое поле для ввода. Если отсутствует компонент редактирования для ввода пароля, отображается сообщение "Значение может отличаться от фактического".
* Разработана страница, содержащая общие настройки сервера приложений.
* Разработана страница, содержащая серверы, зарегистрированные в Сервисе настроек.
* Поддержана возможность прочтения настроек Сервера приложений из {of-mc}.
* Разработана страница "Серверы", на которой отображается список серверов, информация о выбранном сервере и список установленных на нём компонентов.
* Разработан API, позволяющий подключать существующие БД из {of-mc}.
